DROP TABLE IF EXISTS narudzbine;
DROP TABLE IF EXISTS knjige; 
DROP TABLE IF EXISTS autori; 


CREATE TABLE IF NOT EXISTS autori(
	id SERIAL PRIMARY KEY, 
	ime VARCHAR(100) NOT NULL, 
	prezime VARCHAR(100) NOT NULL, 
	drzava VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS knjige(
	id SERIAL PRIMARY KEY,
	autor_id INT NOT NULL REFERENCES autori(id),
	naslov VARCHAR(100) NOT NULL, 
	cena DECIMAL(10,2) NOT NULL,
	godina INT
 );

CREATE TABLE IF NOT EXISTS narudzbine(
	id SERIAL PRIMARY KEY, 
	knjiga_id INT NOT NULL REFERENCES knjige(id),
	kupac_ime VARCHAR(200), 
	datum DATE NOT NULL DEFAULT CURRENT_DATE
);

